name: Build and Push Docker Image to GHCR

on:
  release:
    types: [published]
  workflow_dispatch:
  push:
    paths:
      - 'Dockerfile'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Extract Version from Dockerfile
        id: get_version
        run: |
          VERSION=$(grep 'ARG MEDIAWIKI_VERSION=' Dockerfile | head -n 1 | cut -d '=' -f2 | tr -d '"' | tr -d ' ')
          echo "mw_version=${VERSION}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create GitHub Release
        if: github.event_name != 'release' # Verhindert Ausführung, wenn der Trigger bereits ein Release war
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.mw_version }}
          name: Release ${{ steps.get_version.outputs.mw_version }}
          generate_release_notes: true # Generiert automatisch ein Changelog aus den Commits

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.get_version.outputs.mw_version }}
            type=ref,event=tag
            type=ref,event=branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
